- Dockerfile
- README.md
- rewardbench/__init__.py
- rewardbench/utils.py
- scripts/configs/eval_configs.yaml
- scripts/run_bon.py
- scripts/run_rm.py
- scripts/submit_eval_jobs.py
Closes #90 
Effected models to re-run (prev score --> new score):
* openbmb/UltraRM-13b (69.53 --> 68.18)
* OpenAssistant/oasst-rm-2.1-pythia-1.4b-epoch-2.5 (69.6 --> 69.49)
* OpenAssistant/oasst-rm-2-pythia-6.9b-epoch-1 (62.05 --> 62.23)
* OpenAssistant/reward-model-deberta-v3-large-v2 (57.49 --> 54.29)
* weqweasdas/hh_rlhf_rm_open_llama_3b (54.92 --> 48.85)
* berkeley-nest/Starling-RM-7B-alpha (71.42 --> 71.43)
* PKU-Alignment/beaver-7b-v1.0-reward (47.62 --> 45.44)
* PKU-Alignment/beaver-7b-v1.0-cost (58.25 --> 59.83)
* IDEA-CCNL/Ziya-LLaMA-7B-Reward (63.43 --> 62.94)
These had a stronger effect on Tulu models, interestingly.
> Fix EOS token bug on FastChat models (non DPO)

- scripts/run_bon.py
- scripts/run_rm.py
Resolves #115 
Add `pad_token_id` to model config for models whose config did not contains `pad_token_id`. ex. TinyLlama
> Add `pad_token_id` from tokenizer to model config.

- Dockerfile
- README.md
- rewardbench/generative.py
- scripts/configs/eval_configs.yaml
- scripts/run_generative.py
- scripts/submit_eval_jobs.py
* Add RLHFFlow models to eval script, 
* add new GPT4 versions as a judge, 
* fix launch script
* add prometheus 2 support
> Mixed bag of fixes / updates

- rewardbench/models/__init__.py
- rewardbench/models/grm.py
- scripts/run_rm.py
The Generalizable Reward Model (GRM) aims to enhance the generalization ability of reward models for LLMs through regularizing the hidden states.
Paper: [Regularizing Hidden States Enables Learning Generalizable Reward Model for LLMs](https://arxiv.org/abs/2406.10216). 
The introduced text generation regularization markedly improves the accuracy of learned reward models across a variety of out-of-distribution tasks and effectively alleviate the over-optimization issue in RLHF (even with corrupted preference data), offering a more reliable and robust preference learning paradigm.
This reward model is finetuned from [llama3_8b_instruct](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct) using the [hendrydong/preference_700K](https://huggingface.co/datasets/hendrydong/preference_700K …
> Add GRM classes

- rewardbench/models/grm.py
I noticed that the evaluation results for Ray2333/GRM-Gemma-2B-sftreg differ significantly from my local results due to the padding side issue (I use a batch size of 1, so I didn't encounter this problem). 
This pull request addresses the padding issue by checking the conditions of left and right paddings to correctly project the score from the last token of each prompt-response pair.
> fix padding for GRM class

- scripts/run_rm.py
This PR adds the `attn_implementation` arg mentioned in #169 to allow users to choose between `sdpa`, `eager`, and `flash_attention_2`. If `attn_implementation` is not specified, it falls back to the original behavior, which uses either `sdpa` or `eager`, depending on the PyTorch version.
> Add attn_implementation support

- scripts/configs/eval_configs.yaml
- scripts/submit_eval_jobs.py
> Add models

- rewardbench/rewardbench.py
- setup.py
Would like to get your high-level thoughts. This PR allows us to load model from wandb and save the evaluated results to wandb as well. 
E.g., https://wandb.ai/ai2-llm/open_instruct_internal/runs/u9f16bws?nw=nwusercostah
And then you can do this kind of visualization.
> Support loading model from wandb

- rewardbench/generative.py
- scripts/run_generative.py
Add code support for a new generative model named Con-J-Qwen2-7B, we would like to contribute it to reward-bench.
We can test Con-J-Qwen2-7B by 
```
python scripts/run_generative.py --model="ZiyiYe/Con-J-Qwen2-7B"
```
This is our local test results:
{'Chat': 0.9189944134078212, 'Chat Hard': 0.7982456140350878, 'Safety': 0.8797297297297297, 'Reasoning': 0.881871692039068}
> add_con-j_support_code

- rewardbench/rewardbench.py
Quality of life improvements: It directly pushes the eval results to be visible
E.g., https://huggingface.co/vwxyzjn/rm_zephyr_new
> Support upload metadata to hf

- README.md
- rewardbench/__init__.py
- rewardbench/rewardbench.py
- rewardbench/utils.py
- tests/test_data.py
- tests/test_package.py
Requested by Sander at Cohere, helped by @vwxyzjn 
Example usage:
```
rewardbench --model vwxyzjn/reward_modeling__EleutherAI_pythia-14m --batch_size 128 --tokenizer=EleutherAI/pythia-14m --push_results_to_hub --upload_model_metadata_to_hf --chat_template raw
```
> Add better logging and functionality with instructions to CLI

- rewardbench/models/armorm.py
- rewardbench/rewardbench.py
When a model gives a bfloat16, .numpy() can be unhappy. This happens for e.g. Skywork.
> Tiny dtype fix

- rewardbench/models/__init__.py
- rewardbench/models/qrm.py
- scripts/run_rm.py
Hi, could you please evaluate the QRM reward model: https://huggingface.co/nicolinho/QRM-Llama3.1-8B
I had to add an argument to the script, such that no model kwargs are given to the model_builder as otherwise it messes with the datatypes.
You can run the evaluation with the following command:
```
export ACCELERATE_MIXED_PRECISION=bf16; python run_rm.py  --model nicolinho/QRM-Llama3.1-8B --trust_remote_code --batch_size 1 --attn_implementation flash_attention_2 --no_model_kwargs
```
Thank you!
> Evaluate QRM reward models

- rewardbench/models/__init__.py
- rewardbench/models/qrm.py
- scripts/configs/eval_configs.yaml
Closes #202 (need to run the last two models after auto image completes)
> Configs bump

- rewardbench/models/__init__.py
- rewardbench/models/inform.py
Hi, we trained a new reward model called "INF-ORM-Llama3.1-70B"(https://huggingface.co/infly/INF-ORM-Llama3.1-70B). Now, we need to add a little code in this repo to load and inference our model.
> add model "INF Outcome Reward Model"

- scripts/configs/eval_configs.yaml
- setup.py
Adds configs for new models (and bumps transformers version) and closes #211 , closes #210
> Add model configs and bump transformers version

- rewardbench/models/__init__.py
- rewardbench/models/inform.py
- rewardbench/models/ldlreward.py
- rewardbench/models/lenovo.py
Reward Model based on Label Distribution Learning:
ShikaiChen/LDL-Reward-Gemma-2-27B-v0.1
to run it:
python ./scripts/run_rm.py --model ShikaiChen/LDL-Reward-Gemma-2-27B-v0.1 --batch_size 1
The expected results are:
{
"alpacaeval-easy": 0.99, 
"alpacaeval-hard": 0.9473684210526315,
"alpacaeval-length": 0.9368421052631579,
"donotanswer": 0.8161764705882353,
"hep-cpp": 0.9817073170731707,
"hep-go": 0.9817073170731707,
"hep-java": 0.9939024390243902,
"hep-js": 0.9939024390243902,
"hep-python": 0.975609756097561,
"hep-rust": 0.9573170731707317,
"llmbar-adver-GPTInst": 0.9565217391304348,
"llmbar-adver-GPTOut": 0.8297872340425532,
"llmbar-adver-manual": 0.8478260869565217,
"llmbar-adver-neighbor":0.9104477611940298,
"llmbar-natural": 0.94,
"math-prm": 1.0,
"mt-bench-easy": 1.0, …
> LDL-Reward-Gemma-2-27B-v0.1

- setup.py
@saumyamalik 
Atla Selene-1
To run it:
`python scripts/run_generative.py --model="AtlaAI/Selene-1"`
The json results are:
```
{
"alpacaeval-easy": 0.96,
"alpacaeval-hard": 0.9789473684210527,
"alpacaeval-length": 0.9789473684210527,
"donotanswer": 0.8235294117647058,
"hep-cpp": 0.9695121951219512,
"hep-go": 0.9908536585365854,
"hep-java": 0.9939024390243902,
"hep-js": 0.9695121951219512,
"hep-python": 0.9634146341463414,
"hep-rust": 0.975609756097561,
"llmbar-adver-GPTInst": 0.8586956521739131,
"llmbar-adver-GPTOut": 0.7446808510638298,
"llmbar-adver-manual": 0.7391304347826086,
"llmbar-adver-neighbor": 0.7985074626865671,
"llmbar-natural": 0.98,
"math-prm": 0.9373601789709173,
"mt-bench-easy": 1.0,
"mt-bench-hard": 0.8108108108108109,
"mt-bench-med": 1.0,
"refusals-dangerous": 0.96, …
```
> Add Selene-1 / bump vllm to 0.6.3

- setup.py
Unpinning `tiktoken` to fix dependency issues from #223 , image successfully builds
> unpin tiktoken for vllm compatibility

- rewardbench/rewardbench.py
- scripts/run_generative.py
When using a local or unlisted DPO model, the following error occurs:
`UnboundLocalError: cannot access local variable 'torch_dtype' where it is not associated with a value`
This is due to `torch_dtype` being initialized only within the non-DPO path (`if not is_dpo:`) but being referenced outside of that block.
Initialize `torch_dtype = None` at the start of the `rewardbench(args)` function to ensure the variable exists regardless of model type.
- Fixes RewardBench DPO evaluation with local or custom models
- Maintains compatibility with existing workflows
> Fix UnboundLocalError for torch_dtype in rewardbench.py when using DPO models

- README.md
- rewardbench/generative.py
- rewardbench/generative_v2.py
- rewardbench/utils.py
- scripts/run_generative_v2.py
- scripts/submit_eval_jobs_v2.py
Adds ratings (and therefore ties subset) support for vllm models. Note that with models I've tested, they do pretty poorly in this setting (probably not tuned to give ratings vs. pairwise rankings), but good to have for consistency with API models. This addresses issue #246 and PR #247
> Add ratings and ties support for vllm models
